/*
 * device_defines.h
 *
 *  Created on: 19 Apr 2016
 *      Author: Projectmarch
 */

#ifndef DEVICE_DEFINES_H_
#define DEVICE_DEFINES_H_

#include "xparameters.h"

// DEFAULTS
#define DEFAULT_SLAVE_MASK				0x01

// SPI DEVICES
#define JOINTENCODER_SPI_DEVICE_ID		XPAR_QUAD_SPI_JOINTENCODER_DEVICE_ID
#define MOTORDRIVE_SPI_DEVICE_ID		XPAR_QUAD_SPI_MOTORDRIVE_DEVICE_ID
#define MOTORENCODER_SPI_DEVICE_ID 		XPAR_QUAD_SPI_MOTORENCODER_DEVICE_ID
#define PIGGYBACK_SPI_DEVICE_ID			XPAR_QUAD_SPI_PIGGYBACK_DEVICE_ID
#define SPRINGENCODER_SPI_DEVICE_ID		XPAR_QUAD_SPI_SPRINGENCODER_DEVICE_ID

// GPIO DEVICES
#define BUTTONS_GPIO_DEVICE_ID			XPAR_AXI_GPIO_BUTTONS_DEVICE_ID
#define LEDS_GPIO_DEVICE_ID				XPAR_AXI_GPIO_LEDS_DEVICE_ID
#define MOTORENABLE_GPIO_DEVICE_ID		XPAR_AXI_GPIO_MOTORENABLE_DEVICE_ID
#define PIGGYBACK_GPIO_DEVICE_ID		XPAR_AXI_GPIO_PIGGY_CS_DEVICE_ID

// PWM DEVICES
#define MOTOR_PWM_U_ID					XPAR_TIMER_PWM_U_DEVICE_ID
#define MOTOR_PWM_V_ID					XPAR_TIMER_PWM_V_DEVICE_ID
#define MOTOR_PWM_W_ID					XPAR_TIMER_PWM_W_DEVICE_ID

// PWM FREQUENCY DEFINES
#define MOTOR_PWM_FREQUENCY				20000

#endif /* DEVICE_DEFINES_H_ */
